```python title:iter.py
lista = [5, 6, 3, 2]
it = iter(lista)
print(it) #<list_iterator object at 0x106243828>
print(type(it)) #<class 'list_iterator'>
print(next(it)) #5
print(next(it)) #6
print(next(it)) #3
print(next(it)) #2
print(next(it)) #Error! StopIteration
```

La funci√≥n `iter()` puede recibir un dato iterable y nos devolver√° un iterador del cual podremos acceder a sus elementos mediante la funci√≥n `next()`, cada vez que llamemos la funci√≥n `next()` sobre el iterador nos devolver√° el siguiente elemento del iterador original, por lo tanto si queremos acceder al elemento 4 del iterable original hay que llamar a la funci√≥n `next()` 4 veces, pero si llamamos a `netx()` una quinta vez nos regresar√° un error y el mensaje `StopIteration`.

üè∑Ô∏è: #iter #iterable #iterador #m√©todo #next #StopIteration

üîô [[P-1c6a]]